export const CONSTANTS = {
        SET_USERS_DATA:'SET_USERS_DATA',
        SET_INPUT_NAME: 'SET_INPUT_NAME',
        // SET_FILTERED_BY_NAME:'SET_FILTERED_BY_NAME',
        SET_PAGE: 'SET_PAGE',
        SET_SORTED_PARAM:'SET_SORTED_PARAM',
        SET_USER_INFO:'SET_USER_INFO',
}